package is.svartifoss.sudoku.format;

public enum Glyph {
    RIGHT_HEAVY_DOWN_HEAVY,
    HORIZONTAL_HEAVY,
    HORIZONTAL_HEAVY_DOWN_LIGHT,
    HORIZONTAL_HEAVY_DOWN_HEAVY,
    LEFT_HEAVY_DOWN_HEAVY,
    VERTICAL_HEAVY,
    VERTICAL_LIGHT,
    RIGHT_LIGHT_VERTICAL_HEAVY,
    HORIZONTAL_LIGHT,
    HORIZONTAL_LIGHT_VERTICAL_LIGHT,
    HORIZONTAL_LIGHT_VERTICAL_HEAVY,
    LEFT_LIGHT_VERTICAL_HEAVY,
    RIGHT_HEAVY_VERTICAL_HEAVY,
    HORIZONTAL_HEAVY_VERTICAL_LIGHT,
    HORIZONTAL_HEAVY_VERTICAL_HEAVY,
    LEFT_HEAVY_VERTICAL_HEAVY,
    RIGHT_HEAVY_UP_HEAVY,
    HORIZONTAL_HEAVY_UP_LIGHT,
    HORIZONTAL_HEAVY_UP_HEAVY,
    LEFT_HEAVY_UP_HEAVY
}
